- hosts: all
  vars:
# Avi Controller version can be changed to match any tag from https://hub.docker.com/r/avinetworks/controller/tags
    avi_con_version: 18.1.2-9058-20180623.025526
  tasks:
    - name: Avi Controller | Setup docker
      include_role:
        name: avinetworks.docker
      become: yes
    - name: Avi Controller | Setup Controller
      include_role:
        name: avinetworks.avicontroller
      vars:
        con_image: avinetworks/controller:{{ avi_con_version }}
